### ISSUE TITLE
Please add option to control new terminal  offset.

### ISSUE THREAD

**Issue by zhoupro** [paroxayte/vwm.vim#6]
When I open a bottom terminal, there is no offset, input cursor is out of vision.

**Comment by fireflowerr** [comment]
I'm sorry, your issue is confusing to me. You are going to have to give me a bit more information, although I strongly suspect this request is outside of the scope of this project. Vwm.vim is just a wrapper around `:execute` that create and fills vim windows in a well defined manner. If there is a problem with your cursor going off screen it is more than likely some config unique to your setup.  However if it's a simple tweak to fix your issue and the issue is applicable to others, I don't mind adding some config to the default layout.

**Comment by zhoupro** [comment]
When I open using VwmToggle bot,  Press enter  key until I can't see input line.
<img width="470" alt="屏幕快照 2019-05-15 下午8 08 38" src="https://user-images.githubusercontent.com/10397021/57774535-5c864000-774d-11e9-93d1-ec1c3440ab59.png">
When I resize the window size using maximum button, I can see the bottom input line. 
I don't know the reason. May It's a neovim config problem.
<img width="354" alt="ttt" src="https://user-images.githubusercontent.com/10397021/57774843-2f865d00-774e-11e9-85b7-416cf4283693.png">

**Comment by fireflowerr** [comment]
It looks like vim isn't moving your cursor to a newline when it wraps the line when your window is at that particular size. My guess is that it has something to do with your window manager. Vim should be wrapping the line and moving the buffer view down by 1. The fact that it behaves correctly while max size, but not while in other sizes makes me think the value vim is getting for the window size is a bit off. That is just a guess as I am unable to find a way to replicate your issue on my end.

**Comment by zhoupro** [comment]
Thanks， I will try figure out the reason lately.
